-- =====================================================================
-- Cagnotte café : suivi des contributions et des dépenses de provisions
-- PostgreSQL 14+
-- Convention : montants en centimes (entiers), dates en timestamptz
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Compte de connexion : un compte gère un seul groupe
-- ---------------------------------------------------------------------
CREATE TABLE utilisateur (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(180) NOT NULL UNIQUE,
    mot_de_passe  VARCHAR(255) NOT NULL,
    roles         JSONB        NOT NULL DEFAULT '[]'::jsonb
);

-- ---------------------------------------------------------------------
-- Groupe (étudiants, salariés...) et son mode de gestion
--   CAISSE        : on collecte, on dépense, le payeur est remboursé par la caisse
--   REMBOURSEMENT : on avance l'argent, chacun doit sa part au payeur
-- ---------------------------------------------------------------------
CREATE TABLE groupe (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom              VARCHAR(120) NOT NULL,
    mode             VARCHAR(20)  NOT NULL DEFAULT 'CAISSE',
    proprietaire_id  INTEGER      NOT NULL UNIQUE      -- UNIQUE : 1 compte = 1 groupe
                     REFERENCES utilisateur (id) ON DELETE CASCADE,
    CONSTRAINT ck_groupe_mode CHECK (mode IN ('CAISSE', 'REMBOURSEMENT'))
);

-- ---------------------------------------------------------------------
-- Membre d'un groupe (sans compte de connexion)
-- ---------------------------------------------------------------------
CREATE TABLE membre (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    groupe_id   INTEGER      NOT NULL REFERENCES groupe (id) ON DELETE CASCADE,
    nom         VARCHAR(120) NOT NULL,
    email       VARCHAR(180),
    actif       BOOLEAN      NOT NULL DEFAULT TRUE,
    -- nécessaire pour la clé étrangère composite de "depense"
    CONSTRAINT uq_membre_id_groupe UNIQUE (id, groupe_id)
);
CREATE INDEX idx_membre_groupe ON membre (groupe_id);

-- ---------------------------------------------------------------------
-- Appel à contributions (mode CAISSE) : demande d'argent à tous les membres
-- ---------------------------------------------------------------------
CREATE TABLE appel_contribution (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    groupe_id                   INTEGER      NOT NULL REFERENCES groupe (id) ON DELETE CASCADE,
    titre                       VARCHAR(160) NOT NULL,
    montant_par_membre_centimes INTEGER      NOT NULL CHECK (montant_par_membre_centimes > 0),
    date_limite                 DATE,
    cree_le                     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_appel_groupe ON appel_contribution (groupe_id);

-- ---------------------------------------------------------------------
-- Contribution : ce que doit verser un membre pour un appel
-- payee_le IS NULL => pas encore payée
-- ---------------------------------------------------------------------
CREATE TABLE contribution (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appel_id         INTEGER     NOT NULL REFERENCES appel_contribution (id) ON DELETE CASCADE,
    membre_id        INTEGER     NOT NULL REFERENCES membre (id) ON DELETE CASCADE,
    montant_centimes INTEGER     NOT NULL CHECK (montant_centimes > 0),
    payee_le         TIMESTAMPTZ,
    CONSTRAINT uq_contribution_appel_membre UNIQUE (appel_id, membre_id)
);
CREATE INDEX idx_contribution_membre ON contribution (membre_id);

-- ---------------------------------------------------------------------
-- Dépense = un ticket de caisse saisi par le membre qui a fait les courses
-- remboursee_le IS NULL => le payeur n'a pas encore été remboursé (mode CAISSE)
-- La clé composite garantit que le payeur appartient bien au groupe de la dépense
-- ---------------------------------------------------------------------
CREATE TABLE depense (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    groupe_id       INTEGER      NOT NULL REFERENCES groupe (id) ON DELETE CASCADE,
    paye_par_id     INTEGER      NOT NULL,
    magasin         VARCHAR(120),
    depensee_le     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    total_centimes  INTEGER      NOT NULL CHECK (total_centimes > 0),
    remboursee_le   TIMESTAMPTZ,
    CONSTRAINT fk_depense_payeur_groupe
        FOREIGN KEY (paye_par_id, groupe_id) REFERENCES membre (id, groupe_id)
);
CREATE INDEX idx_depense_groupe ON depense (groupe_id);
CREATE INDEX idx_depense_payeur ON depense (paye_par_id);

-- ---------------------------------------------------------------------
-- Ligne de ticket (facultative : on peut ne saisir que le total)
-- ---------------------------------------------------------------------
CREATE TABLE ligne_depense (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    depense_id       INTEGER      NOT NULL REFERENCES depense (id) ON DELETE CASCADE,
    libelle          VARCHAR(160) NOT NULL,
    quantite         INTEGER      NOT NULL DEFAULT 1 CHECK (quantite > 0),
    montant_centimes INTEGER      NOT NULL CHECK (montant_centimes >= 0)
);
CREATE INDEX idx_ligne_depense ON ligne_depense (depense_id);

-- ---------------------------------------------------------------------
-- Dette (mode REMBOURSEMENT) : part due par un membre au payeur
-- payee_le IS NULL => pas encore réglée
-- ---------------------------------------------------------------------
CREATE TABLE dette (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    depense_id       INTEGER     NOT NULL REFERENCES depense (id) ON DELETE CASCADE,
    debiteur_id      INTEGER     NOT NULL REFERENCES membre (id) ON DELETE CASCADE,
    montant_centimes INTEGER     NOT NULL CHECK (montant_centimes > 0),
    payee_le         TIMESTAMPTZ,
    CONSTRAINT uq_dette_depense_debiteur UNIQUE (depense_id, debiteur_id)
);
CREATE INDEX idx_dette_debiteur ON dette (debiteur_id);

COMMIT;

-- =====================================================================
-- Requêtes utiles (à titre d'exemple)
-- =====================================================================

-- Solde de la caisse d'un groupe (mode CAISSE), en centimes :
--   contributions payées - dépenses déjà remboursées au payeur
--
-- SELECT
--   COALESCE((SELECT SUM(c.montant_centimes)
--             FROM contribution c
--             JOIN appel_contribution a ON a.id = c.appel_id
--             WHERE a.groupe_id = :groupe_id AND c.payee_le IS NOT NULL), 0)
-- - COALESCE((SELECT SUM(d.total_centimes)
--             FROM depense d
--             WHERE d.groupe_id = :groupe_id AND d.remboursee_le IS NOT NULL), 0)
--   AS solde_centimes;

-- Membres en retard de paiement sur les appels échus :
--
-- SELECT m.nom, a.titre, c.montant_centimes
-- FROM contribution c
-- JOIN membre m              ON m.id = c.membre_id
-- JOIN appel_contribution a  ON a.id = c.appel_id
-- WHERE c.payee_le IS NULL
--   AND a.date_limite < CURRENT_DATE
--   AND a.groupe_id = :groupe_id;

-- Ce que chaque membre doit encore (mode REMBOURSEMENT) :
--
-- SELECT m.nom, SUM(dt.montant_centimes) AS du_centimes
-- FROM dette dt
-- JOIN membre m   ON m.id = dt.debiteur_id
-- WHERE dt.payee_le IS NULL AND m.groupe_id = :groupe_id
-- GROUP BY m.nom;
